# ===============================
# Database Configuration
# ===============================

spring.datasource.name=jobportal
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=jobportal;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:remoteuser}
spring.datasource.password=${DB_PASSWORD:remote@321}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# Server Configuration
# ===============================

server.port=8095
server.address=0.0.0.0

# ===============================
# HTTPS Configuration
# ===============================

server.ssl.enabled=true
server.ssl.key-alias=profile-service
server.ssl.key-store=classpath:profile-service.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=remote

# ===============================
# Error Handling
# ===============================

server.error.whitelabel.enabled=false